version: '2'
services:
  gateway:
    image: dockercloud/haproxy
    links:
     - auth-service
     - secondary-service
    ports:
     - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend: 
    container_name: 'frontend'
    image: wookia/rso-frontend:latestdev
    environment:
      PORT: "7373"
    ports:
      - "8080:7373"
    depends_on:
      - auth-service 
      - secondary-service

  auth-service: 
    image: wookia/rso-services-auth:latestdev
    environment: 
      - PORT=8000
      - VIRTUAL_HOST=*/auth, */auth/*
    depends_on:
      - auth-db

  auth-db:
    container_name: 'auth-db'
    image: postgres
    ports:
      - "4321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  secondary-service:
    image: wookia/rso-services-secondary:latestdev
    environment: 
      - PORT=8000
      - VIRTUAL_HOST=*/secondary, */secondary/*
    depends_on:
      - secondary-db

  secondary-db:
    container_name: 'secondary-db'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  adminer:
      image: adminer
      restart: always
      ports:
        - 6060:8080