version: '2'
services:
  gateway:
    container_name: gateway
    build: ./nginx
    ports: 
     - "8000:30" #host:container
    depends_on:
      - auth-service
      - secondary-service

  frontend: 
    container_name: 'frontend'
    image: wookia/rso-frontend:latestdev
    environment:
      PORT: "7373"
    ports:
      - "8080:7373"
    depends_on:
      - auth-service 
      - secondary-service

  auth-service: 
    container_name: 'auth-service'
    image: wookia/rso-services-auth:latestdev
    environment: 
      - PORT=8000
      - DB-PORT=4321
    depends_on:
      - auth-db

  auth-db:
    container_name: 'auth-db'
    image: postgres
    ports:
      - "4321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  secondary-service:
    container_name: 'secondary-service'
    image: wookia/rso-services-secondary:latestdev
    environment: 
      - PORT=8000
      - DB-PORT=5432
    depends_on:
      - secondary-db

  secondary-db:
    container_name: 'secondary-db'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  adminer:
      image: adminer
      restart: always
      ports:
        - 6060:8080