version: '2'
services:
  gateway:
    image: dockercloud/haproxy
    links:
     - auth-service
     - orders-service
     - reservations-service
    ports:
     - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend: 
    container_name: 'frontend'
    image: wookia/rso-frontend:latestdev
    environment:
      PORT: "7373"
    ports:
      - "8080:7373"
    depends_on:
      - auth-service 
      - orders-service

  auth-service: 
    image: wookia/rso-services-auth:latestdev
    environment: 
      - PORT=8000
      - VIRTUAL_HOST=*/auth, */auth/*
    depends_on:
      - auth-db

  auth-db:
    container_name: 'auth-db'
    image: postgres
    ports:
      - "4321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  orders-service:
    image: wookia/rso-services-orders:latestdev
    environment: 
      - PORT=8000
      - VIRTUAL_HOST=*/orders, */orders/*
    depends_on:
      - orders-db

  orders-db:
    container_name: 'orders-db'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  reservations-service:
    image: wookia/rso-services-reservations:latestdev
    environment: 
      - PORT=8000
      - VIRTUAL_HOST=*/reservations, */reservations/*
    depends_on:
      - reservations-db

  reservations-db:
    container_name: 'reservations-db'
    image: postgres
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  adminer:
      image: adminer
      restart: always
      ports:
        - 6060:8080